# This is a basic workflow to help you get started with Actions

name: CI & CD - Release

# Controls when the action will run. 
on:
   push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: '0'
    - name: deploy to heroku app
      uses: akhileshns/heroku-deploy@v3.8.8
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: "ignite-docs-v2-stage"
        heroku_email: "bijay.shah@cygrp.com"
        usedocker: true
